[package]
name = "wasm-nn"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tract = { version = "0.20.21", features = ["onnx"] }
tract-onnx = "0.20.21"
wasm-bindgen = "0.2.88"
getrandom = { version = "0.2", features = ["js"] }
