[package]
name = "candle-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candle-core = "0.3.2"
candle-nn = "0.3.2"
candle-onnx = "0.3.2"
wasm-bindgen = "0.2.88"
prost = "0.12.1"

getrandom = { version = "0.2", features = ["js"] }
